Vagrant.configure("2") do |config|

config.vm.box_check_update = false	
config.vbguest.auto_update = false

config.vm.define "node1" do |node1|
  node1.vm.box = "centos/7"
  node1.vm.hostname = "freeipa.wajtamaka.com"
  node1.vm.network "private_network", ip: "192.168.33.11"
  node1.vm.provider "virtualbox" do |vb|
     vb.name = "node1"
     vb.memory = "2048"
  end
end

config.vm.define "node2" do |node2|
  node2.vm.box = "centos/7"
  node2.vm.hostname = "client.wajatmaka.com"
  node2.vm.network "private_network", ip: "192.168.33.12"
  node2.vm.provider "virtualbox" do |vb|
     vb.name = "node2"
     vb.memory = "512"
  end
end

config.vm.define "node3" do |node3|
  node3.vm.box = "centos/7"
  node3.vm.hostname = "client3.wajatmaka.com"
  node3.vm.network "private_network", ip: "192.168.33.13"
  node3.vm.provider "virtualbox" do |vb|
     vb.name = "node3"
     vb.memory = "512"
  end
end

config.vm.define "xfce" do |xfce|
  xfce.vm.box = "bstoots/xubuntu-16.04-desktop-amd64"
  xfce.vm.hostname = "telco.desk"
  xfce.vm.network "private_network", ip: "192.168.33.14"
  xfce.vm.provider "virtualbox" do |vb|
     vb.name = "xfce"
     vb.memory = "1024"
     vb.gui = true
 end
end
config.vm.define "windows" do |windows|
  windows.vm.box = "icehofman/windows-7-virtualbox"
  windows.vm.hostname = "marketing.desk"
  windows.vm.network "private_network", ip: "192.168.33.15"
  windows.vm.provider "virtualbox" do |vb|
     vb.name = "windows"
     vb.memory = "1024"
     vb.gui = true
 end
end
config.vm.define "mapserver" do |mapserver|
  mapserver.vm.box = "centos/7"
  mapserver.vm.hostname = "mapserver-docker.1rstwap.com"
  mapserver.vm.network "private_network", ip: "192.168.33.16"
  mapserver.vm.provider "virtualbox" do |vb|
     vb.name = "mapserver-docker"
     vb.memory = "2048"
  end
end
config.vm.define "maven" do |maven|
  maven.vm.box = "centos/7"
  maven.vm.hostname = "maven.1rstwap.com"
  maven.vm.network "private_network", ip: "192.168.33.17"
  maven.vm.provider "virtualbox" do |vb|
     vb.name = "maven"
     vb.memory = "2048"
  end
  maven.vm.provision :shell, path: "install-docker.wjt"
end
end
