
Vagrant.configure("2") do |config|

config.vm.box_check_update = false	
config.vbguest.auto_update = false


config.vm.define "jenkins" do |jenkins|
  jenkins.vm.box = "bento/centos-7.3"
  jenkins.vm.hostname = "jenkins.wajatmaka.com"
  jenkins.vm.network "private_network", ip: "192.168.33.10"
  jenkins.vm.provider "virtualbox" do |vb|
     vb.name = "jenkins"
     vb.memory = "1024"
  end
  jenkins.vm.provision "shell", path: "install-server.wjt",privileged: true 
end

config.vm.define "node2" do |node2|
  node2.vm.box = "bento/centos-7.3"
  node2.vm.hostname = "node2.wajatmaka.com"
  node2.vm.network "private_network", ip: "192.168.33.11"
  node2.vm.provider "virtualbox" do |vb|
     vb.name = "node2"
     vb.memory = "1024"
  end
end

config.vm.define "node3" do |node3|
  node3.vm.box = "bento/centos-7.3"
  node3.vm.hostname = "node3.wajatmaka.com"
  node3.vm.network "private_network", ip: "192.168.33.13"
  node3.vm.provider "virtualbox" do |vb|
     vb.name = "node3"
     vb.memory = "1024"
  end
end

end
